version: "3.9"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: popcast_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: popcast_frontend
    restart: always
    ports:
      - "3000:3000" # Default port for Vite dev server
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
