version: "3"

services:
  backend:
    build: ./backend
    container_name: popcast_backend
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - user-facing
      - system-facing

  frontend:
    build: ./frontend
    container_name: popcast_frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - user-facing

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - system-facing
    
  proxy:
    image: nginx:1.21
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - user-facing

volumes:
  postgres-data:
    driver: local

networks:
  user-facing:
  system-facing:
