/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/objects/room/room.glb -o src/components/objects/Room.tsx --types --shadows --transform 
Files: public/objects/room/room.glb [1.98KB] > /home/alean/stuff/apps/popcast-ai/frontend/src/components/objects/room-transformed.glb [1.16KB] (41%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Room(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/objects/room/room-transformed.glb',
  ) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[0, 4, 0]}
        scale={[8, 4, 8]}
      />
    </group>
  )
}

useGLTF.preload('/room-transformed.glb')
