/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/objects/room/room.glb -o src/components/objects/Room.tsx --types --shadows --transform 
Files: public/objects/room/room.glb [1.98KB] > /home/alean/stuff/apps/popcast-ai/frontend/src/components/objects/room-transformed.glb [1.16KB] (41%)
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useTheme } from '../theme-provider'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export default function Room(props: JSX.IntrinsicElements['group']) {
  const { theme } = useTheme()

  const { nodes, materials } = useGLTF(
    '/objects/room/room-transformed.glb',
  ) as GLTFResult

  const lightColor = new THREE.Color(0xffffff)
  const darkColor = new THREE.Color(0x242424)
  
  useEffect(() => {
    if (theme === 'dark') {
      materials.Material.color = darkColor
    } else {
      materials.Material.color = lightColor
    }
  }, [theme])

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[0, 4, 0]}
        scale={[8, 4, 8]}
      />
    </group>
  )
}

useGLTF.preload('/room-transformed.glb')
