/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dock_btn.glb --types --keepnames --shadows --instance --exportdefault --transform --simplify 
Files: dock_btn.glb [536.81KB] > /home/alean/apps/popcast-ai/frontend/public/objects/cdplayer/dock_btn-transformed.glb [521.72KB] (3%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    dock_btn: THREE.Mesh
  }
  materials: {
    ['panasonic_sa-pm02-player']: THREE.MeshPhysicalMaterial
  }
}

export default function DockBtn(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/objects/cdplayer/dock_btn-transformed.glb',
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name='dock_btn'
        receiveShadow
        geometry={nodes.dock_btn.geometry}
        material={materials['panasonic_sa-pm02-player']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/objects/cdplayer/dock_btn-transformed.glb')
