/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/objects/tvs/tvs.glb -o src/components/threejs/TVs3.tsx --types --shadows --transform --exportdefault --keepmeshes 
Files: public/objects/tvs/tvs.glb [66.93KB] > /home/alean/stuff/apps/popcast-ai/frontend/src/components/threejs/tvs-transformed.glb [56.25KB] (16%)
*/

import * as THREE from 'three'
import React from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import Screen from './Screen'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Screen3: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Screen1: THREE.Mesh
    Screen2: THREE.Mesh
    Screen4: THREE.Mesh
  }
  materials: {
    Holzverkleidung: THREE.MeshStandardMaterial
    GlowLampBlue: THREE.MeshStandardMaterial
    HolzverkleidungDark: THREE.MeshStandardMaterial
    blackScreen: THREE.MeshStandardMaterial
    metallArm: THREE.MeshStandardMaterial
    monitoHuelle: THREE.MeshStandardMaterial
    monitoHuelle2: THREE.MeshStandardMaterial
    monitoHuelle2dark: THREE.MeshStandardMaterial
  }
}

export default function TVs(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/objects/tvs/tvs-transformed.glb',
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Holzverkleidung}
        position={[2.008, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.GlowLampBlue}
        position={[2.008, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.HolzverkleidungDark}
        position={[2.008, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        material={materials.blackScreen}
        position={[2.008, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <Screen channelNum={0} position={[0.21, 0, -0.07]} text='Screen 3' />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.metallArm}
        position={[2.008, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.monitoHuelle}
        position={[2.008, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.monitoHuelle2}
        position={[2.008, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.monitoHuelle2dark}
        position={[2.008, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        material={materials.blackScreen}
        position={[2.008, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <Screen channelNum={0} position={[0.21, 0, 2.945]} text='Screen 1' />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        material={materials.blackScreen}
        position={[2.008, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <Screen channelNum={0} position={[-4.218, 0, 2.945]} text='Screen 2' />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        material={materials.blackScreen}
        position={[2.008, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <Screen channelNum={0} position={[-4.218, 0, -0.07]} text='Screen 4' />
      </mesh>
    </group>
  )
}

useGLTF.preload('/objects/tvs/tvs-transformed.glb')
